duodigit/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('number.urls')),
    # path('admin/', admin.site.urls), # DESATIVAR O ADMIN
]

number/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('history/', views.history, name='history'),
]

number/models.py
from django.db import models
from django.utils import timezone
from django import forms


class Number(models.Model):
    numbers = models.CharField(max_length=8)
    smallduodigit = models.CharField(max_length=8, default=0)
    date_time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.numbers


class FormVerificador(forms.ModelForm):
    class Meta:
        model = Number
        exclude = ('date_time', 'smallduodigit',)

number/views.py
from django.shortcuts import render, redirect
from . models import Number
from django.core.paginator import Paginator
from django.contrib import messages
from . models import FormVerificador
import sys


# funcao verificadora do menor duodigito
def SmallDuodigit(number):
    for num in range(2, sys.maxsize**10):
        multiple = int(number) * num
        if Duodigit(multiple):
            return multiple


# funcao verificadora de duodigito
def Duodigit(digit):
    value = str(digit)
    repeated = []
    distinct = 0

    for num in value:
        if num not in repeated:
            distinct += 1
        repeated.append(num)

    if 2 >= distinct:
        return True
    else:
        return False


def index(request):
    if request.method != 'POST':
        form = FormVerificador()
        return render(request, 'number/index.html', {'form': form})

    form = FormVerificador(request.POST, request.FILES)
    number = request.POST.get('numbers')

    # verificacoes do input do usuario
    if number.isnumeric():
        # verificar se eh menor que 100 ou se o primeiro digito e 0 para corrigir o problema de input do html
        if int(number) <= 100 or int(number[0]) == 0:
            messages.add_message(request, messages.ERROR, 'Digite um número maior que 100!')
            return render(request, 'number/index.html', {'form': form})

        # forma a mensagem do menor duodigito
        multiple = f'O menor duodigito múltiplo de {number} é {SmallDuodigit(number)}'
        messages.add_message(request, messages.SUCCESS, multiple)

        alteracoes = Number(numbers=request.POST['numbers'], smallduodigit=SmallDuodigit(number))

        if form.is_valid():
            alteracoes.save()
            return redirect('index')
    else:
        messages.add_message(request, messages.ERROR, 'Digite um número inteiro!')
        return render(request, 'number/index.html', {'form': form})


def history(request):
    # faz a ordenacao por data e a divisao de paginas
    numbers = Number.objects.order_by('-date_time')
    paginator = Paginator(numbers, 6)
    page = request.GET.get('p')
    numbers = paginator.get_page(page)
    return render(request, 'number/history.html', {
        'numbers': numbers
    })

number/templates/number/history.html
{% extends 'base.html' %}

{% block conteudo %}

<div class="container pt-3 mt-5 mb-2 d-flex justify-content-center col-sm-6">
    <div class="card px-1 py-1 shadow-lg">
        <div class="card-body">

            <!-- Historico -->
            <h4 class="card-title mb-3 text-dark"><strong>Histórico</strong></h4>
            <p><i>Página {{numbers.number}}</i></p>
            <table class="table caption-top table-striped">
              <thead>
                <tr>
                  <th class="text-dark" scope="col">Número</th>
                  <th class="text-dark" scope="col">Menor Duodigito</th>
                  <th class="text-dark mob-hide" scope="col">Data</th>
                  <th class="text-dark mob-hide" scope="col">Hora</th>
                </tr>
              </thead>
              <tbody>
                {% for number in numbers %}
                    <tr>
                      <td class="">{{number.numbers}}</td>
                      <td class="">{{number.smallduodigit}}</td>
                      <td class="mob-hide">{{number.date_time|date:'d/m/Y'}}</td>
                      <td class="mob-hide">{{number.date_time|date:'H:i'}}</td>
                    </tr>
                {% endfor %}
              </tbody>
            </table>
            <div class="d-flex flex-column text-center text-dark"> <small class="agree-text">Desafio <a class="text-dark" href="https://bridge.ufsc.br/" target="_blank"><u>Bridge</u></a> Dev Web Full-Stack</small></div>
        </div>
    </div>
</div>

<!-- Paginacao -->
<div class="container d-flex justify-content-center">
    <nav aria-label="Page navigation example">
      <ul class="pagination">
          {% for page in numbers.paginator.page_range %}
                {% if numbers.number == page %}
                    <li class="page-item active shadow-lg"><a class="page-link text-dark shadow-lg" href="?p={{page}}">{{page}}</a></li>
                {% else %}
                    <li class="page-item shadow-lg"><a class="page-link text-dark shadow-lg" href="?p={{page}}">{{page}}</a></li>
                {% endif %}
          {% endfor %}
      </ul>
    </nav>
</div>

{% endblock %}

number/templates/number/index.html
{% extends 'base.html' %}

{% block conteudo %}

<div class="container pt-3 mt-5 mb-3 d-flex justify-content-center col-sm-6">
    <div class="card px-1 py-1 shadow-lg">
        <div class="card-body">

            <!-- Apresentacao -->
            <div class="container mt-3 mb-5 d-flex justify-content-center">
                <div class="card px-1 py-1 shadow-lg">
                    <div class="card-body pt-0 pb-0">
                        <h4 class="card-title mt-3 text-dark"><strong>Menor Duodigito</strong></h4>
                        <p>Este <a class="text-dark" href="https://rockcontent.com/br/blog/progressive-web-apps/" target="_blank"><u>Progressive Web App (PWA)</u></a> consiste em calcular o <strong>menor número real duodigito múltiplo de X</strong>, onde <strong>X</strong> é um número <strong>real > 100</strong> informado pelo usuário.</p>
                        <p><i>* Um número duodigito é aquele cujo seus algarismos têm no máximo 2 distintos números. *</i></p>
                    </div>
                </div>
            </div>

            <!-- Formulario para insercao de numeros -->
            <h6 class="information mt-4 text-dark">Digite um número ( X )</h6>
            <form method="POST" action="{% url 'index' %}">
                {% csrf_token %}
                <div class="row justify-content-center">
                    <div class="col-sm-8">
                        <div class="form-group">
                          <input class="form-control shadow-lg" maxlength="8" type="text" name="numbers" value="{{request.POST.number}}" placeholder="Ex: 1034" required id="id_numbers">
                        </div>
                    </div>
                </div>

                <div class="row justify-content-center">
                    <div class="col-sm-5">
                      <button type="submit" class="btn btn-primary btn-block confirm-button shadow-lg">Verificar</button>
                    </div>
                </div>
            </form>

            <!-- Mensagens -->
            <div class="container pt-3 mb-0 d-flex justify-content-center">
                {% if messages %}
                {% for message in messages %}
                    <div class="alert {{ message.tags }}" role="alert">{{ message }}</div>
                {% endfor %}
                {% endif %}
            </div>

            <!-- Rodape -->
            <div class="d-flex flex-column text-center text-dark"> <small class="agree-text">Desafio <a class="text-dark" href="https://bridge.ufsc.br/" target="_blank"><u>Bridge</u></a> Dev Web Full-Stack</small></div>

        </div>
    </div>
</div>

{% endblock %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="pt-br">
<head>
    <title>Projeto</title>
    {% include 'parciais/_head.html' %}
</head>

<body class="text-center bg-primary bg-gradient">

  {% include 'parciais/_nav.html' %}
  {% block conteudo %}{% endblock %}
</body>
</html>

templates/parciais/_head.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">
<!-- Bootstrap core CSS -->
<link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'style.css' %}" rel="stylesheet">

templates/parciais/_nav.html
{% load static %}



<nav class="navbar navbar-light bg-white shadow-lg">
  <a class="navbar-brand text-dark" href="{% url 'index'%}"><h3 class="font-weight-bold">Duodigito<strong class="text-primary">_</strong></h3></a>
  <a class="navbar-brand text-primary" href="{% url 'history'%}"><h3 class="font-weight-bold">Histórico</h3></a>
</nav>